# system do zarządzania dockerami (kontener dockerów)

#### Ukrywanie hasla  #####
x-environment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


###########################
services:
  postgis:
    build:
      context: .. #project working directory
      dockerfile: docker/postgis/Dockerfile
    image: 'prge-postgis'   # a.k.a przepis na ciasto
    container_name: prge-postgis-$${{ENV_NAME}} # a. k.    ciasto
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${ENV_PORT}:5432
    volumes:
      - postgis-local-data:/var/lib/postgresql/data
  geoserver:
    build:
      context: ..
      dockerfile: docker/geoserver/Dockerfile
    image: 'prge_2025_geoserver'
    container_name: 'prge_2025_geoserver'
    ports:
      - 9000:8080
    volumes:
      - ../.tmp/data:/opt/geoserver_data
      - ../.tmp/geoserver-config:/opt/geoserver/data_dir


volumes: #Pozwala kontenerowi widzieć co siędzieje na moim dysku twardym komputera
  postgis-local-data:
