# system do zarządzania dockerami (kontener dockerów)

#### Ukrywanie hasla  #####
x-environment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


###########################
services:
  postgis:
    build:
      context: .. #project working directory
      dockerfile: docker/postgis/Dockerfile
    image: 'prge-postgis'   # a.k.a przepis na ciasto
    container_name: prge-postgis-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgis-local-data:/var/lib/postgresql/data

volumes: #Pozwala kontenerowi widzieć co siędzieje na moim dysku twardym komputera
  postgis-local-data:
